name = "signalhub"
main = "src/index.js"
compatibility_date = "2024-12-01"

[[d1_databases]]
binding = "DB"
database_name = "signalhub-db"
database_id = "8e139b48-0911-4dce-9529-9cee10d3a3ec"

[[kv_namespaces]]
binding = "SUMMARY_KV"
id = "5acd6d5f43ef49d0b8e493c422008c8e"

[ai]
binding = "AI"
